<<<<<<< HEAD
=======
import { Playfair_Display, Poppins } from "next/font/google";
>>>>>>> 0c3feb4d082c7e17efa3e96b10bcda7d7ac2743f
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< HEAD
=======
// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   weight: ["600", "700"],
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500"],
// });
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-playfair",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-poppins",
});

>>>>>>> 0c3feb4d082c7e17efa3e96b10bcda7d7ac2743f
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

=======
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: "Swastik Hotel – Near Ram Jhula & Janki Setu | Rishikesh",
  description:
    "Comfortable and affordable stay near Ram Jhula and Ganga in Rishikesh. AC rooms, WiFi, parking. Book directly on WhatsApp.",
};


>>>>>>> 0c3feb4d082c7e17efa3e96b10bcda7d7ac2743f
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
    
        <body className={`${poppins.variable} ${playfair.variable} font-sans`}>

>>>>>>> 0c3feb4d082c7e17efa3e96b10bcda7d7ac2743f
        {children}
      </body>
    </html>
  );
}
