import { Playfair_Display, Poppins } from "next/font/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   weight: ["600", "700"],
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500"],
// });
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-playfair",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: "Swastik Hotel – Budget Hotel Near Ram Jhula | Rishikesh",
  description:
    "Affordable hotel near Ram Jhula and Janki Setu in Rishikesh. AC rooms, free WiFi, family-friendly stay near Ganga. Book rooms directly on WhatsApp.",
  keywords: [
    "Swastik Hotel Rishikesh",
    "Hotel near Ram Jhula",
    "Budget hotel Rishikesh",
    "Hotel near Ganga Rishikesh",
    "Stay near Janki Setu",
    "Hotel Swastik",
    "hotel swastik"
  ],
  verification: {
    google: "R2_bu2bt-3In3mNp8nJNR3AdobPZ3ti_VPrTVe5a-hI",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
    <body className={`${poppins.variable} ${playfair.variable} font-sans`}>

  <script
    type="application/ld+json"
    dangerouslySetInnerHTML={{
      __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Hotel",
        name: "Swastik Hotel",
        telephone: "+91 9756066660",
        address: {
          "@type": "PostalAddress",
          addressLocality: "Rishikesh",
          addressRegion: "Uttarakhand",
          addressCountry: "India"
        },
        url: "https://thehotelswastik.com"
      })
    }}
  />

  {children}

</body>
 
    </html>
  );
}
